services:
  back:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: back
    tty: true 
    volumes: # プロジェクトのコードを/src/backにマウント
      - ./:/src/back
    environment:
      MYSQL_USER: user
      MYSQL_PASS: password
      MYSQL_HOST: mysql
      MYSQL_DBNAME: memo_db
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
    networks:
      - go_network

  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: front
    tty: true
    environment: 
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src/front
    depends_on: 
      - mysql
    networks:
      - go_network

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: memo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d 
    networks:
      - go_network

volumes:
  mysql:

networks:
  go_network:
    driver: bridge